# Injected by CI/CD or docker-compose
spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# Slightly verbose logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.com.epam=DEBUG
logging.file.name=./logs/gym-app.log

# Pretty JSON
spring.jackson.serialization.indent-output=true

# Health checks and Metrics (actuator)
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,loggers

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

security.jwt.secret=${JWT_SECRET}
security.jwt.lifetime=30m
security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
